In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
EXCEL_NAME = "Production  Vendor Wise Item Rate 05062026 184415.xlsx"
df_of_interest = pd.read_excel(EXCEL_NAME, header=0)
df_of_interest

,VendorName,ItemCode,Vendor Unit,TranUnitCode,Name,Rate,ValidFrom,Create By,CreatedDate,Update By,UpdatedDate
0,JYOTI ENTERPRISE (LABOUR),BHC-180-060-122-080-45-D09,NaN,Nos,Lathe + Drill + Tapp + Chamf,50.0,2025-05-30,Jaydip Jw,2025-05-30,Jaydip Jw,2025-05-30
1,AVANTIKA ENGINEERING,BHC-300-127-210-181-90-M16,NaN,Nos,Lathe + Drill + Tapp + Chamf,130.0,2020-10-01,Yogesh Jw,2020-10-01,Jaydip Jw,2024-11-20
2,RAM SHREE INDUSTRIES LABOUR,BHC-300-127-210-181-90-M16,NaN,Nos,Lathe + Drill + Tapp + Chamf,107.0,2021-02-24,Yogesh Jw,2021-02-24,Yogesh Jw,2021-02-24
3,VISHWAKARMA ENTERPRISE LABOUR,BHC-101.5M-101.6-100-146-90-M12,NaN,Nos,Lathe + Drill + Tapp + Chamf,50.0,2023-03-28,Yogesh Jw,2021-01-28,Jaydip Jw,2024-12-25
4,COLT HYDROMATICS PVT LTD,BHC-101.5M-101.6-100-146-90-M12,NaN,Nos,Lathe + Drill + Tapp + Chamf,1.0,2022-11-18,Paras Qc,2022-11-18,Paras Qc,2023-01-20
...,...,...,...,...,...,...,...,...,...,...,...
10419,RAVI ENGINEERING WORKS LABOUR,XJTH-48-PB-70,NaN,Nos,HOBBING,13.0,2020-06-04,Aks,2020-06-04,Jigar Qc,2022-05-05
10420,RAVI ENGINEERING WORKS LABOUR,XJTH-65-PB-100,NaN,Nos,HOBBING,30.0,2020-06-04,Aks,2020-06-04,Jigar Qc,2022-05-05
10421,JAY MATAJI ENGINEERING WORKS,JTH-24-24-26,NaN,Nos,HOBBING,10.0,2020-06-18,Aks,2020-06-18,Jigar Qc,2022-06-06
10422,JAY MATAJI ENGINEERING WORKS,XJTH-19-19-50,NaN,Nos,HOBBING,8.0,2021-01-29,Yogesh Jw,2021-01-29,Jigar Qc,2022-06-06
10423,BHOOMI ENGINEERING WORKS,BF-110x050x036-M,NaN,Nos,Facing / Milling,20.0,2024-05-27,Prakash,2024-05-27,Prakash,2024-05-27

In [6]:
df_of_interest["CreatedDate"] = pd.to_datetime(df_of_interest["CreatedDate"], errors="coerce")
df_of_interest = df_of_interest.sort_values("CreatedDate", na_position="last").reset_index(drop=True)
df_of_interest.to_excel("df-jobwork.xlsx", index=False)
df_of_interest

,VendorName,ItemCode,Vendor Unit,TranUnitCode,Name,Rate,ValidFrom,Create By,CreatedDate,Update By,UpdatedDate
0,RC ELECTRONICS INDUSTRIES,XMB-B-093-01-M,NaN,Nos,Blackodising,193.50,2026-05-26,Aks,2020-05-25,Renil Jw,2026-05-26
1,JAY MATAJI ENGINEERING WORKS,XJTH-28-28-40,NaN,Nos,HOBBING,10.00,2020-05-26,Administrator,2020-05-26,Jigar Qc,2022-06-06
2,PAYAL INDUSTRIES LABOUR,"XFL-3/4"" BSP-T-CI-U",NaN,Nos,CED Coating-Black,4.21,2020-05-26,Administrator,2020-05-26,Administrator,2020-05-26
3,NEEL ENGINEERING LABOUR,BF-170x110x110-M,NaN,Nos,Shapping,140.00,2020-05-26,Administrator,2020-05-26,Administrator,2020-05-26
4,RAMDEV ENGINEERING LABOUR,XJTH-28-28-40,NaN,Nos,CNC - 1,12.00,2020-05-26,Administrator,2020-05-26,Akg,2024-08-20
...,...,...,...,...,...,...,...,...,...,...,...
10419,AVANTIKA ENGINEERING,BHC-300-070-210-103-60-D09,Nos,Nos,Lathe - 1,139.10,2026-06-03,Renil Jw,2026-06-03,Renil Jw,2026-06-03
10420,AAI SHREE KHODIYAR INDUSTRIES,"TBS-05x1/2"" BSP",NaN,Nos,CNC - 1,8.00,2026-06-05,Renil Jw,2026-06-05,Renil Jw,2026-06-05
10421,Shivam Engineering Works Labour,C-16-T-LNT,NaN,Nos,Milling,2.00,2026-06-05,Renil Jw,2026-06-05,Renil Jw,2026-06-05
10422,Sm Enterprise Labour,BF-735x100x100-M,NaN,mm,Shapping,0.25,2026-06-05,Renil Jw,2026-06-05,Renil Jw,2026-06-05
10423,AAI SHREE KHODIYAR INDUSTRIES,"WN-2"" BSP",NaN,Nos,CNC - 1,18.00,2026-06-05,Renil Jw,2026-06-05,Renil Jw,2026-06-05