In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
EXCEL_NAME = "Sales Invoice Register 2020-2026 Mitesh 260508.xlsx"
df = pd.read_excel(EXCEL_NAME, header=0)

In [6]:
df.columns

Index(['SupplierCode', 'SupplierName', 'Gst_No', 'Invoice_No.', 'Invoice Date',
       'ItemType', 'MainGroup', 'SubMainGroup', 'Barcode', 'Item_code',
       'Invoice Qty', 'Unit', 'Standard Rate', 'Invoice Rate', 'YearId',
       'Disc.Per', 'Amount', 'TransporterName', 'Destination'],
      dtype='str')

In [11]:
df_of_interest = df[["SupplierName", "Gst_No", "Invoice_No.", "Invoice Date", "SubMainGroup", "Item_code", "Invoice Qty", "Standard Rate", "Invoice Rate", "Disc.Per", "TransporterName", "Destination", "Amount"]].copy()
df_of_interest.to_excel("df_of_interest.xlsx", index=False)

In [ ]:
df.rename(columns={ 'Invoice lines/Partner':'Customer',
                    'Unnamed: 6': 'Product_Name',
                    'Invoice/Bill Date': 'Invoice_Date',
                    'Invoice lines/Product':'Product_Id'}, inplace=True)
# df['Product_Name'] = df['Product_Name'].str.lstrip()

In [21]:
df.Product_Name.value_counts()

Product_Name
BELL HOUSING                            9458
GEAR PUMP                               4011
SUCTION STRAINER                        2642
GEAR COUPLING WITH BORE & KEYWAY        2570
MANYFOLD BLOCK                          2394
                                        ...
GIFT ARTICLE                               1
Y - FLOW CONTROL VALVE                     1
HU - SECTIONAL DIRE CON VALVES ( W )       1
JAW COUPLING                               1
4WE CORE                                   1
Name: count, Length: 246, dtype: int64

In [31]:
df[df.Product_Name == 'BELL HOUSING']

,Number,Invoice_Date,Customer,GSTIN,Salesperson,Product_Id,Product_Name,Invoice lines/Quantity,Invoice lines/Discount (%),Invoice lines/Sales Order Lines/Discount (%),Payment Terms,Is Whatsapp Sent,Invoice lines/Last Updated by,Invoice lines/Last Updated on
0,J/2026/03/1242,2026-03-30,SHINE TRADERS,24ADGFS4973B1Z4,SALES04-BHADRESH,BHCK-180-082.6-110( 28+17.46 )( 106.2*90`*M10 ),BELL HOUSING,5.0,35.0,35.0,45 Days,0.0,BHERU SF,2026-03-30 18:02:43
1,J/2026/03/1242,2026-03-30,SHINE TRADERS,24ADGFS4973B1Z4,SALES04-BHADRESH,BHCK-180-082.6-110( 28+17.46 )( 106.2*90`*M10 ),BELL HOUSING,5.0,35.0,35.0,NaN,NaN,BHERU SF,2026-03-30 18:02:43
18,J/2026/03/1237,2026-03-30,ATUL TECHNICAL SERVICES (Dadra And Nagar Haveli),26BUBPS8109Q1ZX,SALES06-RAVI,BHAK-250-082.6-190-106.2-90-M10-J48-42+17.46-7...,BELL HOUSING,1.0,14.0,14.0,NaN,NaN,LR ANAND,2026-03-30 18:06:55
67,J/2026/03/1233,2026-03-30,TECHNO ENTERPRISES (SANGLI) (Sangli),27CMJPS6872F1ZF,SALES09-ANJU,BHAK-130-082.6-100-106.2-90-M10-J28-24+17.46-4...,BELL HOUSING,4.0,14.0,14.0,NaN,NaN,BHERU SF,2026-03-30 15:33:09
68,J/2026/03/1233,2026-03-30,TECHNO ENTERPRISES (SANGLI) (Sangli),27CMJPS6872F1ZF,SALES09-ANJU,BHAK-130-082.6-080-106.2-90-M10-J19-19+13.45-2...,BELL HOUSING,2.0,14.0,14.0,NaN,NaN,BHERU SF,2026-03-30 15:33:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52518,J/2025/04/0011,2025-04-01,LUCKY INDUSTRIES (HALOL) (Panch Mahals),24AADFL9646A1ZI,SALES04-BHADRESH,BHCK-180-082.6-122( 28+15.88 )( 106.2*90`*M10 ),BELL HOUSING,1.0,27.0,27.0,30 Days,1.0,OdooBot,2025-09-03 12:05:14
52534,J/2025/04/0007,2025-04-01,ASIAN ELECTRIC CO (Mahesana),24AADFA2612D1ZB,DAYA SHIROYA,BHA-180-082.6-110-106.2-90-M10,BELL HOUSING,10.0,30.0,30.0,NaN,NaN,OdooBot,2025-09-03 12:05:14
52535,J/2025/04/0006,2025-04-01,LAXMAN KADVA AND SONS PVTLTD (Surendranagar),24AACCM5710C1Z3,SALES04-BHADRESH,BHA-110-082.6-075-106.2-90-M10,BELL HOUSING,10.0,32.0,32.0,NaN,1.0,OdooBot,2025-09-03 12:05:14
52543,J/2025/04/0005,2025-04-01,GAYATRI ENTERPRISE (JAMNAGAR) (Jamnagar),24ABYPV8697D1ZL,Kruti Buha,BHAK-130-082.6-080-106.2-90-M10-J19-19+13.45-2...,BELL HOUSING,1.0,25.0,25.0,NaN,NaN,OdooBot,2025-09-03 12:05:14
52545,J/2025/04/0004,2025-04-01,NORTHERN HYDRAULICS (Ludhiana),03AADFN6738P1ZU,SALES04-BHADRESH,BHA-180-095-124-127.3-45-M10,BELL HOUSING,10.0,35.0,35.0,NaN,1.0,OdooBot,2025-09-03 12:05:14

In [27]:
df.groupby('Product_Name').agg({'Invoice lines/Quantity':'sum'}).sort_values(by='Invoice lines/Quantity', ascending=False)

                                Invoice lines/Quantity
Product_Name
SCRAPS                                        85997.82
PIPE CLAMP                                    78217.00
BELL HOUSING                                  57304.00
PLASTIC PART                                  54199.00
DOWTY SEAL                                    32904.00
...                                                ...
Y - FLOW CONTROL VALVE                            1.00
EDM PAPER FILTER                                  1.00
EPE - WELDED DIAPH ACCUMULATOR                    1.00
4WE BODY                                          1.00
4DL LEVER                                         1.00

[246 rows x 1 columns]

In [33]:
month_enum = df.Invoice_Date.dt.month
df[df.GSTIN == '24ADGFS4973B1Z4'].groupby(month_enum).agg({'Invoice lines/Quantity':'sum'})

              Invoice lines/Quantity
Invoice_Date
1                             2383.0
2                             1731.0
3                             1947.0
4                             1619.0
5                             1686.0
6                             1892.0
7                             2111.0
8                             2243.0
9                             2522.0
10                            2183.0
11                            2639.0
12                            2124.0

In [34]:
df_old = pd.read_excel('sales invoice register 200501 to 250831.xlsx')
df_old

,Invoice No,Invoice Date,Customer Code,GSTIN,Customer Name,Product Name,ItemCode,TranQty,Rate,Dis %,BaseAmount,TaxableValue,SalesPerson,FINANCIAL YEAR,Unnamed: 14
0,SI10000001,2020-05-09,NaN,24AACCA0194N1ZO,AMMANN INDIA PRIVATE LIMITED,GEAR COUPLING WITH BORE & KEYWAY,JT-28( 25.4{M8*90'x2}+17.46{M8*90'x2} )( 40+40 ),20.0,407.0,27.0,5942.2,5942.2,NaN,20-21,NaN
1,SI10000002,2020-05-11,NaN,24AACCA0194N1ZO,AMMANN INDIA PRIVATE LIMITED,H - SOL. OPE. DIRECTIONAL VALVE,H--4WE-06-G-RAC220,2.0,3290.0,27.0,4803.4,4803.4,NaN,20-21,NaN
2,SI10000003,2020-05-11,NaN,24AACCA0194N1ZO,AMMANN INDIA PRIVATE LIMITED,H - SOL. OPE. DIRECTIONAL VALVE,H--4WE-06-G-RAC220,2.0,3290.0,27.0,4803.4,4803.4,NaN,20-21,NaN
3,SI10000004,2020-05-11,NaN,26AADFH2629H1ZJ,HL EQUIPMENTS,BLANKING PLUG,"BP-1/8"" BSP",30.0,15.0,25.0,337.5,337.5,NaN,20-21,NaN
4,SI10000004,2020-05-11,NaN,26AADFH2629H1ZJ,HL EQUIPMENTS,BLANKING PLUG,"CP-1/8"" BSP",22.0,19.0,25.0,313.5,313.5,NaN,20-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269442,SI10005751,2025-08-22,SD00000668,24AAPFM9186L1ZF,MASK HYDRAULICS MACHINERIES,SAE FLANGE WITH BOLT KIT,"FL-1 1/4"" BSP-T-CI-U",3.0,560.0,27.0,1226.4,1226.4,SALES04-BHADRESH,25-26,NaN
269443,SI10005751,2025-08-22,SD00000668,24AAPFM9186L1ZF,MASK HYDRAULICS MACHINERIES,GEAR PUMP,1P-4090--C-P-S-T-B2-D,1.0,4300.0,27.0,3139.0,3139.0,SALES04-BHADRESH,25-26,NaN
269444,SI10005751,2025-08-22,SD00000668,24AAPFM9186L1ZF,MASK HYDRAULICS MACHINERIES,BELL HOUSING,BHCK-250-101.6-180( 42+22.22*4.76 )( 146*90`*M...,1.0,5050.0,27.0,3686.5,3686.5,SALES04-BHADRESH,25-26,NaN
269445,SI10005751,2025-08-22,SD00000668,24AAPFM9186L1ZF,MASK HYDRAULICS MACHINERIES,BELL HOUSING,BHAK-130-082.6-080-106.2-90-M10-J19-19+17.46-2...,1.0,1010.0,27.0,737.3,737.3,SALES04-BHADRESH,25-26,NaN
269446,SI10005751,2025-08-22,SD00000668,24AAPFM9186L1ZF,MASK HYDRAULICS MACHINERIES,GEAR PUMP,1P-4020--C-P-S-T-B2-D,1.0,3100.0,27.0,2263.0,2263.0,SALES04-BHADRESH,25-26,NaN

In [39]:
df_old.columns

Index(['Invoice No', 'Invoice Date', 'Customer Code', 'GSTIN', 'Customer Name',
       'Product Name', 'ItemCode', 'TranQty', 'Rate', 'Dis %', 'BaseAmount',
       'TaxableValue', 'SalesPerson', 'FINANCIAL YEAR', 'Unnamed: 14'],
      dtype='str')

In [42]:
df_old[df_old["Customer Name"] == 'SHINE TRADERS']["Product Name"].value_counts()
# df_old["Customer Name"].value_counts(

Product Name
BELL HOUSING                        2794
GEAR COUPLING WITH BORE & KEYWAY     930
GEAR PUMP                            863
PIPE CLAMP                           402
FILLER BREATHER ASSEMBLY             379
                                    ...
MALE BRANCH TEE                        1
DIRECTION CONTROL VALVES               1
PRESSURE RELIEF VALVE                  1
HOUSING FOR PRV                        1
TANK BREATHER                          1
Name: count, Length: 84, dtype: int64

In [1]:
df

NameError: name 'df' is not defined

In [15]:
df_of_interest[df_of_interest["SupplierName"] == 'TECHNO AGENCY'].tail()

,SupplierName,Gst_No,Invoice_No.,Invoice Date,SubMainGroup,Item_code,Invoice Qty,Standard Rate,Invoice Rate,Disc.Per,TransporterName,Destination,Amount
264479,TECHNO AGENCY,24BTPPS2497J1ZW,SI10014525,2026-03-23,MALE STUD COUPLING,"GE-08 SX1/4"" BSP",25.0,63.0,63.0,30.0,ALPESH ROADWAYS,RAJKOT CITY,1102.5
264531,TECHNO AGENCY,24BTPPS2497J1ZW,SI10014824,2026-03-30,FLOW CONTROL VALVE,"DRV-10X3/8"" BSP",15.0,1030.0,1030.0,30.0,ALPESH ROADWAYS,RAJKOT CITY,10815.0
264711,TECHNO AGENCY,24BTPPS2497J1ZW,SI10000507,2026-04-15,Z - BMR ORBIT HYD. MOTOR,BMRY-200-P1-AII-Y,4.0,10200.0,10200.0,32.0,ALPESH ROADWAYS,RAJKOT CITY,27744.0
264847,TECHNO AGENCY,24BTPPS2497J1ZW,SI10001215,2026-05-02,GEAR COUPLING WITH BORE & KEYWAY,JTS-28,50.0,70.0,70.0,30.0,ALPESH ROADWAYS,RAJKOT CITY,2450.0
264873,TECHNO AGENCY,24BTPPS2497J1ZW,SI10001327,2026-05-06,Z - BMM ORBIT HYD. MOTOR,BMM-50-P1-C-Y1,2.0,9600.0,9600.0,32.0,ALPESH ROADWAYS,RAJKOT CITY,13056.0

In [ ]:
invoice number, 
invoice date, 
standard rate, 
invoice rate,
quantity,
discount,
transporter name, destination
item code,
submaingroup,

In [ ]:
columns_of_interest = ["Invoice Number", "Invoice Date", "Invoice Qty", "Standard Rate", "Invoice Rate", "Disc.Per", "Item Code", "SubMainGroup", "Transporter Name", "Destination"]