In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
INVOICE_NO_COL = "Invoice_No."
INVOICE_DATE_COL = "Invoice Date"
STANDARD_RATE_COL = "Standard Rate"
INVOICE_RATE_COL = "Invoice Rate"
QUANTITY_COL = "Invoice Qty"
DISCOUNT_COL = "Disc.Per"
TRANSPORTER_NAME_COL = "TransporterName"
DESTINATION_COL = "Destination"
ITEM_CODE_COL = "Item_code"
AGG_COL = "Amount"
PRODUCT_COL = "SubMainGroup"
GST_COL = "Gst_No"
CUSTOMER_COL = "SupplierName"
columns_of_interest = [
    INVOICE_NO_COL,
    INVOICE_DATE_COL,
    CUSTOMER_COL,
    GST_COL,
    ITEM_CODE_COL,
    PRODUCT_COL,
    QUANTITY_COL,
    STANDARD_RATE_COL,
    INVOICE_RATE_COL,
    DISCOUNT_COL,
    TRANSPORTER_NAME_COL,
    DESTINATION_COL,
    AGG_COL
]

In [3]:
EXCEL_NAME = "Sales Invoice Register 2020-2026 Mitesh 260508.xlsx"
df = pd.read_excel(EXCEL_NAME, header=0)

In [4]:
FILE_NAME = "Sales Invoice Register 2014 2020 Mitesh 260509.xlsx"
df_old = pd.read_excel(FILE_NAME, header=0)

In [5]:
df_old.rename(columns={'Sub Main Group':'SubMainGroup'}, inplace=True)

In [6]:
df_20_25 = df[columns_of_interest]
df_14_20 = df_old[columns_of_interest]

In [7]:
df_of_interest = pd.concat([df_14_20, df_20_25], ignore_index=True)
df_of_interest[INVOICE_DATE_COL] = pd.to_datetime(df_of_interest[INVOICE_DATE_COL], errors="coerce")
df_of_interest = df_of_interest.sort_values(INVOICE_DATE_COL, na_position="last").reset_index(drop=True)
df_of_interest.to_excel("df_of_interest.xlsx", index=False)
df_of_interest

,Invoice_No.,Invoice Date,SupplierName,Gst_No,Item_code,SubMainGroup,Invoice Qty,Standard Rate,Invoice Rate,Disc.Per,TransporterName,Destination,Amount
0,SI00000009,2014-04-01,ASIAN TUBE LTD.(UNIT-I),24AABCA2797E1ZV,PCH-20-GR2-PP,PIPE CLAMP,10.0,0.0,81.0,30.0,,NaN,567.00
1,SI00000008,2014-04-01,SIT FLEXIBLE HOSE PVT LTD,24AAKCS2010H1ZS,H--4WE-10-D-G24,H - SOL. OPE. DIRECTIONAL VALVE,2.0,0.0,5110.0,27.0,,NaN,7460.60
2,SI00000009,2014-04-01,ASIAN TUBE LTD.(UNIT-I),24AABCA2797E1ZV,"DS-1"" BSP",DOWTY SEAL,10.0,0.0,10.0,30.0,,NaN,70.00
3,SI00000009,2014-04-01,ASIAN TUBE LTD.(UNIT-I),24AABCA2797E1ZV,"DS-1/2"" BSP",DOWTY SEAL,10.0,0.0,7.0,30.0,,NaN,49.00
4,SI00000009,2014-04-01,ASIAN TUBE LTD.(UNIT-I),24AABCA2797E1ZV,"HN-1"" BSPX1"" BSP",HEX NIPPLE,10.0,0.0,94.0,30.0,,NaN,658.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
561809,SI10001637,2026-05-14,CORE HYDRAULICS PVT LTD,24AABCH4876M1Z7,BHA-130-082.6-100-106.2-90-M10,BELL HOUSING,15.0,750.0,815.0,12.0,-,NaN,10758.00
561810,SI10001636,2026-05-14,LEXUS HYCON PRIVATE LIMITED,24AACCL2622G1ZZ,HL--TIF2-04 B-P25,HL - RETURN LINE FILTER,1.0,1217.0,1217.0,25.0,-,NaN,912.75
561811,SI10001636,2026-05-14,LEXUS HYCON PRIVATE LIMITED,24AACCL2622G1ZZ,FSB-05-N-NC,FILLER BREATHER ASSEMBLY,1.0,260.0,260.0,30.0,-,NaN,182.00
561812,SI10001652,2026-05-14,SN HYDRAULICS(MAHARASHTRA),27EKHPS7454F1ZN,JT-28--28+13.45--40+40,GEAR COUPLING WITH BORE & KEYWAY,10.0,530.0,530.0,30.0,-,NaN,3710.00
561813,SI10001660,2026-05-14,EXCEL HYDRAULIC (SURAT),24AOJPV6539G1ZI,DPRH-10-S-100,PRESSURE RELIEF VALVE,15.0,1950.0,1950.0,40.0,-,NaN,17550.00

In [4]:
df_of_interest = pd.read_excel('df_of_interest.xlsx')

In [8]:
df_of_interest[df_of_interest["Invoice_No."] == "SI10014020"]

,Invoice_No.,Invoice Date,SupplierName,Gst_No,Item_code,SubMainGroup,Invoice Qty,Standard Rate,Invoice Rate,Disc.Per,TransporterName,Destination,Amount
349447,SI10014020,2022-03-21,ARUN HYDRAULICS (SALE),24AAMFA5605P1Z6,"FL-1 1/2"" BSP-T-CI-U",SAE FLANGE WITH BOLT KIT,20.0,650.0,650.0,22.0,DOOR DELIVERY,AHMEDABAD,10140.0
349458,SI10014020,2022-03-21,ARUN HYDRAULICS (SALE),24AAMFA5605P1Z6,BHAK-180-060-124-080-45-D09-J28-28+18-40+40,BELL HOUSING,5.0,1580.0,1580.0,22.0,DOOR DELIVERY,AHMEDABAD,6162.0
349528,SI10014020,2022-03-21,ARUN HYDRAULICS (SALE),24AAMFA5605P1Z6,BHAK-180-101.6-110-146-90-M12-J28-28+22.22*6.3...,BELL HOUSING,2.0,1720.0,1720.0,22.0,DOOR DELIVERY,AHMEDABAD,2683.2
349540,SI10014020,2022-03-21,ARUN HYDRAULICS (SALE),24AAMFA5605P1Z6,MB-A-010-04-M,MANYFOLD BLOCK,2.0,1905.0,1905.0,22.0,DOOR DELIVERY,AHMEDABAD,2971.8
400856,SI10014020,2023-03-13,SHREE SHYAM ENGINEERING CO,24AHHPK8722F1ZF,PM--PG-100-BT-210,PRESSURE GAUGE - PRE MASS,2.0,1155.0,1155.0,25.0,TIRUPATI COURIER SERVICE PVT.LTD,UMARGAON CITY,1732.5
453860,SI10014020,2024-03-16,SUNWORLD INDUSTRIES,24EDBPK0937C1Z2,1P-3044+0P-3006--C-P-S-TT-B2-E,GEAR PUMP ( MULTI COMBINATION ),1.0,9350.0,9350.0,30.0,DOOR DELIVERY,AHMEDABAD,6545.0
505581,SI10014020,2025-03-22,FINE BEARING AND OIL SEAL STORE,03AAIFF3105H1ZZ,DM-6-600-SL2B-D40,D - DM R P HYD. MOTOR,2.0,47150.0,47150.0,40.0,NAGPAL CARGO MOVERS,LUDHIYANA,56580.0
553143,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,2P-3120+1P-3052--C-P-S-ST-B2-E,GEAR PUMP ( MULTI COMBINATION ),4.0,17000.0,17000.0,40.0,-,NaN,40800.0
553194,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,BHA-250-101.6-190-146-90-M12,BELL HOUSING,6.0,2930.0,2930.0,40.0,-,NaN,10548.0
553195,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,1P-4090+1P-4090--C-P-S-TT-B2-E,GEAR PUMP ( MULTI COMBINATION ),2.0,9100.0,9100.0,40.0,-,NaN,10920.0
553207,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,2P-3146+1P-3090--C-P-S-ST-B2-E,GEAR PUMP ( MULTI COMBINATION ),4.0,17000.0,17000.0,40.0,-,NaN,40800.0
553208,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,BHA-180-082.6-110-106.2-90-M10,BELL HOUSING,30.0,910.0,910.0,40.0,-,NaN,16380.0
553209,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,1P-4017+1P-4017--C-P-S-TT-B2-E,GEAR PUMP ( MULTI COMBINATION ),2.0,9100.0,9100.0,40.0,-,NaN,10920.0
553234,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,MB-A-003-02-M,MANYFOLD BLOCK,10.0,2720.0,2720.0,40.0,-,NaN,16320.0
553240,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,0P-3006--C-P-S-T-B1-N,GEAR PUMP,6.0,2670.0,2670.0,40.0,-,NaN,9612.0
553248,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,BHA-130-060-130-080-45-D09,BELL HOUSING,1.0,800.0,800.0,40.0,-,NaN,480.0
553250,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,DPRH-06-K-315,PRESSURE RELIEF VALVE,13.0,820.0,820.0,40.0,-,NaN,6396.0
553276,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,2P-3158+1P-3090--C-P-S-ST-B2-E,GEAR PUMP ( MULTI COMBINATION ),2.0,17000.0,17000.0,40.0,-,NaN,20400.0
553290,SI10014020,2026-03-07,PRIME HYDRAULIC & PNEUMATICS (P) LTD,03AABCP0755B1Z4,1P-4072+1P-4072--C-P-S-TT-B2-E,GEAR PUMP ( MULTI COMBINATION ),2.0,9100.0,9100.0,40.0,-,NaN,10920.0

In [29]:
df_of_interest[df_of_interest["SupplierName"].str.contains("KRISH")]

,Invoice_No.,Invoice Date,SupplierName,Gst_No,Item_code,SubMainGroup,Invoice Qty,Standard Rate,Invoice Rate,Disc.Per,TransporterName,Destination,Amount
776,SI00000204,2014-04-08,SHREE KRISHANA ENTERPRISE ( BAKORL),24AGXPP1327Q1ZM,"RHZ-20 SX3/4"" BSP-0.5",CHECK VALVE ( TUBE CONNECTION ),1.0,0.0,690.0,32.0,,NaN,469.2
2591,SI00000683,2014-04-24,SHREE KRISHANA ENTERPRISE ( BAKORL),24AGXPP1327Q1ZM,"DRV-20X1"" BSP",FLOW CONTROL VALVE,1.0,0.0,1600.0,32.0,,NaN,1088.0
2685,SI00000702,2014-04-25,KRISHNA PLASTIC ENGINEERING,NaN,B--DSG-03-3C60-A220-N,B - SOL. OPE. DIRECTIONAL VALVE,1.0,0.0,6760.0,32.0,,NaN,4596.8
2686,SI00000702,2014-04-25,KRISHNA PLASTIC ENGINEERING,NaN,H--EDG-01-H-1-P08-T10-20,H - PROPORTIONAL PRE. RELIEF VALVE,1.0,0.0,8615.0,32.0,,NaN,5858.2
3230,SI00000858,2014-05-02,SHREE KRISHANA ENTERPRISE ( BAKORL),24AGXPP1327Q1ZM,MB-B-46-03,MANYFOLD BLOCK,1.0,0.0,12500.0,0.0,,NaN,12500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
522930,SI10001256,2026-05-04,KRISH HYDRAULICS,24AAKFK6985G1ZW,"SOV-1/4"" BSP-R",NIDDLE VALVE,38.0,495.0,495.0,38.0,H.H ROADWAYS,RAJKOT CITY,11662.2
522933,SI10001232,2026-05-04,KRISH HYDRAULICS,24AAKFK6985G1ZW,BHC-250-101.6-175-146-90-M12,BELL HOUSING,5.0,3220.0,3220.0,38.0,H.H ROADWAYS,RAJKOT CITY,9982.0
522966,SI10001247,2026-05-04,KRISH HYDRAULICS,24AAKFK6985G1ZW,"SOV-1/4"" BSP-R",NIDDLE VALVE,60.0,495.0,495.0,38.0,H.H ROADWAYS,RAJKOT CITY,18414.0
522967,SI10001232,2026-05-04,KRISH HYDRAULICS,24AAKFK6985G1ZW,"DRV-12X1/2"" BSP",FLOW CONTROL VALVE,13.0,1270.0,1270.0,38.0,H.H ROADWAYS,RAJKOT CITY,10236.2
523008,SI10001247,2026-05-04,KRISH HYDRAULICS,24AAKFK6985G1ZW,SPL-NG 06-BLIND-MS,SUB PLATE,10.0,420.0,420.0,38.0,H.H ROADWAYS,RAJKOT CITY,2604.0